name: NPM Publish Next

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish_next:
    if: github.repository_owner == 'viamrobotics'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: make build

      - name: Publish (dry run)
        id: check_new_version
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: next
          dry-run: true

      - name: Validate version name
        if: ${{ steps.check_new_version.outputs.type }}
        shell: bash
        run: |
          if [[ ! "$(npm pkg get version)" =~ ^\"[0-9]+\.[0-9]+\.[0-9]\-next\.[0-9]+\"$ ]]; then
            echo "::error::Cannot publish an off-cycle version named: $(npm pkg get version). Please run 'make bump-next-version' to generate a valid version name."
            exit 1
          fi

      - name: Publish
        if: ${{ steps.check_new_version.outputs.type }}
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: next
